apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-mail
  labels:
    app: discord-mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-mail
  template:
    metadata:
      labels:
        app: discord-mail
    spec:
      imagePullSecrets:
      - name: ghcr-auth-tmcp
      containers:
      - name: discord-mail
        image: '${REGISTRY_URL}:${IMAGE_TAG}'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2525
        envFrom:
        - configMapRef:
            name: discord-mail-config
        - secretRef:
            name: discord-mail-secret
        env:
        - name: WEB_PORT
          value: "3000"
        - name: BASE_URL
          value: "https://mail.raegous.dev"
        volumeMounts:
        - name: email-storage
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: email-storage
        persistentVolumeClaim:
          claimName: discord-mail-pvc
