apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-mail
  labels:
    app: discord-mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-mail
  template:
    metadata:
      labels:
        app: discord-mail
    spec:
      imagePullSecrets:
      - name: ghcr-auth-tmcp
      containers:
      - name: discord-mail
        image: '${REGISTRY_URL}:${IMAGE_TAG}'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2525
        envFrom:
        - configMapRef:
            name: discord-mail-config
        - secretRef:
            name: discord-mail-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'echo "QUIT" | nc localhost 2525 | grep -q "221"'
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'echo "QUIT" | nc localhost 2525 | grep -q "221"'
          initialDelaySeconds: 15
          periodSeconds: 20 
