replicaCount: 1

image:
  repository: discord-mail
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  ports:
    smtp:
      port: 25
      targetPort: 2525
      protocol: TCP
  # HTTP port for internal cluster communication (used by ingress)
  httpPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: mail.raegous.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - raegous.dev
        - mail.raegous.dev
      secretName: discord-mail-tls

persistence:
  enabled: true
  size: 5Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

config:
  emailStoragePath: "/app/email-storage"
  maxEmailsPerUser: 100
  maxEmailSize: 10485760  # 10MB in bytes
  smtpPort: 2525
  smtpHost: "0.0.0.0"
  baseUrl: "https://mail.raegous.dev"
  tls:
    enabled: true  # Set to true if you want to enable TLS
    secretName: "discord-mail-tls"  # Name of the TLS secret created by cert-manager
