replicaCount: 1

image:
  repository: discord-mail
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: mail.raegous.com
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  size: 5Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

config:
  emailStoragePath: "/app/email-storage"
  maxEmailsPerUser: 100
  maxEmailSize: 10485760  # 10MB in bytes 