apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: smtp
      port: {{ .Values.service.ports.smtp.port }}
      targetPort: {{ .Values.service.ports.smtp.targetPort }}
      protocol: {{ .Values.service.ports.smtp.protocol }}
    - name: http
      port: 80
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }} 