name: Deploy to Kubernetes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify cluster connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Update image in deployment manifest
        run: |
          export REGISTRY_URL=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          export IMAGE_TAG=${{ github.sha }}

          # Replace variables in all Kubernetes files
          for file in k8s/*.yaml; do
            envsubst < $file > ${file}.updated
            mv ${file}.updated $file
          done

      - name: Apply k8s manifests
        run: |
          export KUBECONFIG=~/.kube/config
          # Apply Kubernetes configurations
          for file in k8s/*.yaml; do
            echo "Checking changes for $file..."
            kubectl diff -f "$file" > /dev/null
            if [ $? -eq 0 ]; then
              echo "No changes detected in $file, skipping apply."
            else
              echo "Changes detected in $file, applying..."
              kubectl apply --server-side -f "$file"
            fi
          done
